# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby "2.6.5"

gem "sinatra", "~> 2.0"
gem "sinatra-contrib", "~> 2.0"

gem "puma", "~> 4.2"

gem "sqlite3", "~> 1.4"
